### ISSUE TITLE
my brother in christ you removed the pgp from your website

### ISSUE THREAD

**Issue by Dario48true** [VilariStorms/VilariStorms#1]
the pgp is not on the website, so pwese either update the readme to say it's missing or put it back on 🥺the second is the better one imo🥹

**Comment by VilariStorms** [comment]
From where exactly?
https://vilari.be.sexy and https://vilari.be.sexy/pgp.txt are both still up?
I presume you mean https://vilari.site/ which I decided to use for my blog. I have fixed https://vilari.site/pgp.txt which I forgot to restore which I switched hosting providers.

**Comment by VilariStorms** [comment]
Oh, I see. Did you mean from apt.vilari.site? That's fixed now, my bad
